language: java
jdk:
- openjdk8
os:
- linux
cache:
  directories:
  - "$HOME/.m2"
env:
  global:
    - CODECOV_TOKEN=f1f9df08-dc5a-485d-8ea8-bcf963a62003
install:
  mvn --settings .maven.xml install -DskipTests=true -Dgpg.skip -Dmaven.javadoc.skip=true -B -V
script: |-
  mvn clean install -Plocal || travis_terminate 1
  log=$(git log $TRAVIS_COMMIT_RANGE --oneline)
  echo $'Commit message: '$TRAVIS_COMMIT_MESSAGE
  echo $'**Change log:**<br/>'${log//$'\n'/<br/>}
after_success:
  - bash <(curl -s https://codecov.io/bash)
branches:
  only:
  - master
before_deploy: |-
  log=$(git log $TRAVIS_COMMIT_RANGE --oneline)
  export TAG=$'v'$TRAVIS_COMMIT_MESSAGE
  export BODY=$'**Change log:**<br/>'${log//$'\n'/<br/>}
  mvn help:evaluate -N -Dexpression=project.version|grep -v '\['
  export project_version=$(mvn help:evaluate -N -Dexpression=project.version|grep -v '\[')
  echo $GPG_SECRET_KEYS | base64 --decode | $GPG_EXECUTABLE --import
  echo $GPG_OWNERTRUST | base64 --decode | $GPG_EXECUTABLE --import-ownertrust
deploy:
  - provider: releases
    skip_cleanup: true
    api_key:
      secure: hwjCU0E+BPY/7QP0VeoLBrieKemH/mj+7qvkqTyCS3CrBGrdojle0Zxb9zKe8KAEM4aWbvC36bMh/X/PjO/nC2o/2TF+Xkh+d0S7D44enkLqW1jl3hOzAWg8rl6OAHxcWAxNbp9iRNR5yh2Vr535D0cmKJ7XhtWATfsT7utmvIZLo233p9TIKCjzFlU9+owBrVHlzNa5huTHLA2f2HKzUN3gsMS2M3jdhZS1xZh2vFugccHS4xT1wUBkKipVH76fqi6mTcNIpeD86/ZSGYGWW0CnWX96UOdJHgMhUyTSCOdsLEZte2N2z2vF2K3JFNifL3sodx8SdJRSIuHS0HCaQahmLQ3FvBhMDoT2b5CrIoP83iIyOGp3R1743Rzr+X1FGW2egNq5ry+KpBvN0kBgGKdadKZFGPgmRk38CuntwL3OMlz7EC2dAWV782I+TB3/cVWzW+ZGTChdZkGDtxHFzuiOKge0Yyls84hWae0qvPxZzZKjfthi+yhbs0aiXSFsl6lXfDXWF+V5+eJOu8p1g72PkFbEzqyXl+wD+n1Rjyum01qBhRcMpZBQnONVtH4WDYyazntsUCZCzftMWWJkC9U9qL9YxObpGCLDvUarj8OFYTHT4NG8t66Y1FQFpOcPfLonp//Nqtt6riTTE823D3IukeqMg6wmt8bzuoxK6qI=
    file:
      - README.md
      - target/broken-xml-$project_version.jar
    name: Release $TRAVIS_COMMIT_MESSAGE
    tag_name: $TAG
    body: $BODY
    on:
      repo: cqfn/broken-xml
      branch: master
      condition: "$TRAVIS_COMMIT_MESSAGE =~ ^([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3})$"
  - provider: script
    skip_cleanup: true
    script: mvn clean deploy --settings .maven.xml -B -U -Prelease
    on:
      repo: cqfn/broken-xml
      branch: master
      condition: "$TRAVIS_COMMIT_MESSAGE =~ ^([0-9]{1,3}).([0-9]{1,3}).([0-9]{1,3})$"
